### ISSUE TITLE
Enable 'starboard_exporter_vulnerabilityreport_image_vulnerability'

### ISSUE THREAD

**Issue by SadFaceSmith** [giantswarm/starboard-exporter#124]
By default I do not see this metric (starboard_exporter_vulnerabilityreport_image_vulnerability) exposed. Is there a way to enable it?

I only have these two: 

starboard_exporter_configauditreport_resource_checks_summary_count
starboard_exporter_vulnerabilityreport_image_vulnerability_severity_count

**Comment by stone-z** [comment]
Hi @SadFaceSmith, you're correct, we don't expose detail metrics by default because they [can be problematic](https://github.com/giantswarm/starboard-exporter#a-note-on-cardinality), particularly for larger environments.

To enable the detail metrics, simply start the exporter with a list of target labels you'd like to be exposed for each vulnerability. Some examples are available under [Customization](https://github.com/giantswarm/starboard-exporter#customization)

**Comment by SadFaceSmith** [comment]
Excellent! Thanks!
