### ISSUE TITLE
Wrong metrics name in helm charts grafana dashboard

### ISSUE THREAD

**Issue by Arabus** [giantswarm/starboard-exporter#41]
The grafana dashboard provided with the helm chart uses the wrong metrics name [here](https://github.com/giantswarm/starboard-exporter/blob/main/helm/starboard-exporter/templates/grafana-dashboard.yaml#L601):

```
          "targets": [
            {
              "exemplar": true,
              "expr": "topk(10, sum(starboard_exporter_vulnerabilityreport_image_vulnerability{severity=~\"CRITICAL|HIGH\"}) by (image_repository, image_tag))",
              "format": "table",
              "instant": true,
              "interval": "",
              "legendFormat": "",
              "refId": "A"
            }
          ],
```

it should rather be:

```
          "targets": [
            {
              "exemplar": true,
              "expr": "topk(10, sum(starboard_exporter_vulnerabilityreport_image_vulnerability_severity_count{severity=~\"CRITICAL|HIGH\"}) by (image_repository, image_tag))",
              "format": "table",
              "instant": true,
              "interval": "",
              "legendFormat": "",
              "refId": "A"
            }
          ],
```

This breaks the the "Pods with Critical/High CVEs Panel".

**Comment by stone-z** [comment]
Hey @Arabus, thanks for bringing it to our attention

This panel was originally intended to use CVSS scores reported by individual metrics, as opposed to the counts reported by summaries. That approach got dropped along the way though since we don't want to require individual metrics by default, so it makes sense to just show the summary numbers here. Summing CVSS scores is of pretty questionable value anyway, it should've at least been a `count` :man_shrugging:
