### ISSUE TITLE
feat: Add starboard-exporter helm chart to ArtifactHub

### ISSUE THREAD

**Issue by dirien** [giantswarm/starboard-exporter#58]
hi GiantSwarm,

would be dope to have the `starboard-exporter` in ArtifactHub, so more people could find this awesome project!

![image](https://user-images.githubusercontent.com/38325136/152419511-a2db47f4-0341-40d6-a8f6-81dfeefbf3f7.png)

https://artifacthub.io/packages/search?ts_query_web=starboard-exporter&sort=relevance&page=1

**Comment by stone-z** [comment]
Hey @dirien, great idea! We're interested and are planning to add it. I've not worked much with ArtifactHub and my initial attempt to add `starboard-exporter` was not successful, but stay tuned.

**Comment by dirien** [comment]
If you need help, let me know. Theoretically you just need to enter the helm repo url.

**Comment by stone-z** [comment]
I suspect it is failing because we do some [templating in the Chart](https://github.com/giantswarm/starboard-exporter/blob/2a399de6ae4ae431bc3f7a220c92416502b9c0c4/helm/starboard-exporter/Chart.yaml#L7), supported by our [opinionated builder](https://github.com/giantswarm/architect). We have [an alternative](https://github.com/giantswarm/app-build-suite) we are starting to adopt for cases like this so I will probably need to migrate this repo to use that before we can add it to ArtifactHub. Both are on the team's todo list

**Comment by dirien** [comment]
hi @stone-z,

thanks for the feedback! Will close the issue then.  Looking forward!
