### ISSUE TITLE
Image Repository does not include registry

### ISSUE THREAD

**Issue by cnwaldron** [giantswarm/starboard-exporter#62]
The image repository field does not include the registry path. It cuts off the repository to only include the project/image name. It would be very helpful to include the registry in this field to help track the exact image down. 

Expected:
image_repository=custom.repo.com/library/image

Actual result:
image_repository=library/image

**Comment by cnwaldron** [comment]
Realized this is an issue with Starboard as they don't store that information.

**Comment by stone-z** [comment]
Hey @cnwaldron, thanks for your suggestion! Exposing the image registry would be a useful addition.

Rather than adding the registry to the `image_repository` label, I think it would be nice to be able to query and bucket it on its own, so I'm adding it as a new label `image_registry` in https://github.com/giantswarm/starboard-exporter/pull/65.

Hopefully that also meets your use case? Feedback welcome

**Comment by stone-z** [comment]
I went ahead and released the `image_registry` label in https://github.com/giantswarm/starboard-exporter/releases/tag/v0.3.0 so I'll close this issue. Feel free to holler if we can do better :slightly_smiling_face:
