### ISSUE TITLE
Feature: add other reports

### ISSUE THREAD

**Issue by albertschwarzkopf** [giantswarm/starboard-exporter#81]
Hi,

is it possible to implement the other starboard reports:

- [ ] kubehunterreports
- [x] ciskubebenchreports https://github.com/giantswarm/starboard-exporter/pull/118
- [x] configauditreports https://github.com/giantswarm/starboard-exporter/pull/72

**Comment by stone-z** [comment]
Hi @albertschwarzkopf yes it's planned, and in fact there is already [a PR for `ConfigAuditReports`](https://github.com/giantswarm/starboard-exporter/pull/72). We are currently waiting to merge because upstream is changing the format of those reports to drop the existing Polaris format. Once there is an upstream release with the new format, we'll continue.

**Comment by CoReYeDe** [comment]
![image](https://user-images.githubusercontent.com/22613068/161027286-50f30a81-30fd-4129-a6bb-88fe58687aa3.png)

ciskubebenchreports are mentioned on your page, but actually, it seems to be not implemented..
Just a hint :)

**Comment by stone-z** [comment]
Heh. You got us @CoReYeDe :wink: the docs were faster than the PRs. Thank you for reading them! 
ConfigAuditReports were [added a moment ago](https://github.com/giantswarm/starboard-exporter/pull/72), stay tuned for CIS benchmarks

**Comment by skuethe** [comment]
Is this something which is already being worked on (metrics for `ciskubebenchreports`)? Or is it open for contribution?
Just checking in, because there doesn't seem to be any open PR for this.

CC @mycodeself because you mentioned that you are also planing on implementing this [here](https://github.com/giantswarm/starboard-exporter/pull/72#issue-1152048167)

**Comment by stone-z** [comment]
Hey @skuethe thanks for your interest in the project. We are currently preoccupied with customer requests elsewhere, but as a rough estimate we think we'll have bandwidth for someone to start the CIS controller the week after next, so starting May 9th (obligatory disclaimer: planning is hard, other stuff might come up, but we'd like to do it then if we can).

That said, we're definitely open to contributions if someone would like to open a PR before then.

**Comment by fhielpos** [comment]
`CISKubeBenchReports` have been added to the exporter as part of https://github.com/giantswarm/starboard-exporter/pull/118

We have released `starboard-exporter v0.5.0` with this new feature 😄

**Comment by stone-z** [comment]
Upstream is replacing `starboard` with `trivy-operator` and has [removed the kubehunter plugin](https://github.com/aquasecurity/trivy-operator/pull/68). It isn't clear from their [public discussions](https://github.com/aquasecurity/starboard/discussions/1173) whether/when they plan to provide an alternative for that functionality, so I'm hesitant to invest much in exporting their kubehunter reports right now. 

If someone has time to implement the functionality for the sunset period of starboard we'd be open to a PR, otherwise I'd suggest we close this and re-evaluate once the future of kubehunter in trivy-operator is more clear. It is functionality I would also like to have, so I hope they do include it. @albertschwarzkopf are you already using starboard to run kubehunter scans? If so, I'd be interested in hearing what you do about them in the meantime.

If there are no objections/better ideas, I'll consider this closed and we can keep an eye on kubehunter upstream.

**Comment by stone-z** [comment]
Perfect. Then we'll close this and keep and watch for kubehunter capabilities in the future. Thanks, everyone!
